import 'package:flutter/material.dart';
import 'package:tic_tac_toe/screens/main_screen.dart';
import 'package:tic_tac_toe/theme/theme.dart';
import 'package:tic_tac_toe/widgets/wallpaper.dart';

// 👇 NEW imports
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_auth/firebase_auth.dart';

Future<void> main() async {
  // 👇 Needed before using any Firebase APIs
  WidgetsFlutterBinding.ensureInitialized();

  // 👇 Initialize Firebase using the options generated by flutterfire configure
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 👇 Give every device a uid (for multiplayer later)
  await FirebaseAuth.instance.signInAnonymously();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tic-Tac-Toe',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      builder: (context, child) {
        return Wallpaper(child: child!);
      },
      home: const MainScreen(),
    );
  }
}
